# Generated by Django 5.2.4 on 2025-07-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=36),
        ),
    ]
